### ISSUE TITLE
Changing the caret color

### ISSUE THREAD

**Issue by mgroth0** [daniel3735928559/guppy#194]
I've tried 
```css 
caret-color: white;
``` 
with all the css selectors but its not working.

**Comment by mgroth0** [comment]
made progress with 
```css
 .guppy_active .main_cursor {
    caret-color: white;
	color: white;
	background-color: white;
	border: 1px solid white;
  }
  .guppy_inactive .main_cursor {
    caret-color: white;
	color: white;
	background-color: white;
	border: 1px solid white;
	
  }
```
but it still doesn't look right. there's still some black in the cursor
