### ISSUE TITLE
changing the color doesnt effect the fraction bar

### ISSUE THREAD

**Issue by mgroth0** [daniel3735928559/guppy#197]
I inverted my colors: 
```css
.guppy_active {
      background-color: black;
      color: cyan;
  }

  .guppy_inactive {
      background-color: black;
      color:cyan;
  }
```

It mostly works but the fraction bar stayed black:

(ignore the yellow border, which is unrelated)
<img width="204" alt="Screen Shot 2021-05-23 at 8 18 26 PM" src="https://user-images.githubusercontent.com/12831489/119281530-0a156f00-bc04-11eb-8e23-63b26cc0c20b.png">
